### PR TITLE
WIP: Add support for OpenSSL v1.1.0

### LINKED ISSUE #405: OpenSSL 1.1.0e make error, why?
GCC 4.9.2
Perl 5.20.3
OpenSSL 1.1.0.e

[root@Server_centos rabbitmq-c-master]# make
make  all-am
make[1]: Entering directory `/backup/rabbitmq-c-master'
  CC       librabbitmq/librabbitmq_librabbitmq_la-amqp_openssl_bio.lo
librabbitmq/amqp_openssl_bio.c: In function 'amqp_openssl_bio_init':
librabbitmq/amqp_openssl_bio.c:143:50: error: invalid application of 'sizeof' to incomplete type 'BIO_METHOD'
   memcpy(&amqp_bio_method, BIO_s_socket(), sizeof(amqp_bio_method));
                                                  ^
make[1]: *** [librabbitmq/librabbitmq_librabbitmq_la-amqp_openssl_bio.lo] Error 1
make[1]: Leaving directory `/backup/rabbitmq-c-master'
make: *** [all] Error 2

### LINKED ISSUE #438: Minimum OpenSSl version supported on Windows 10 x64
The ReadMe note says rabbitmq-c works with openSSL v0.9.8+ but I have runtime issues with the openSSL version used on our Windows application (v1.0.1e). We will patch to the latest version of SSL later this month but I thought of bringing this up since the library is not compatible with v1.0.1. Having said that, openSSL stopped support for v1.0.1 end of Dec 2016 and suggest using v1.0.2 or v.1.1.0.

### PR DESCRIPTION
**Pull request by alanxz**
Add support for OpenSSL v1.1.0

* [x] Make necessary changes to compile against v1.1.0
* [ ] Add support for compiling against OpenSSL v1.1.0 in travis/linux environment
* [ ] Add support for compiling against OpenSSL v1.1.0 in appveyor/win32 environment
* [ ] Add support for running SSL-based test in travis/linux environment

Fixes #405 
Fixes #438

---
This change is [Reviewable](https://reviewable.io/reviews/alanxz/rabbitmq-c/471)

### CODE REVIEW

**Comment by macintoshplus** [comment]
Hi,
Need you help for merge this pool request ?

I need the php-amqp ext for close the PHP 7.2 migration.
Thanks for your job.

**Comment by alanxz** [comment]
@macintoshplus the bit this is missing is setting up travis so that rabbitmq-c can compile against OpenSSL v1.1.0 on travis. I'd be willing to take contributions that make that happen (sadly I haven't had a lot of time to devote to this recently).

**Comment by macintoshplus** [comment]
@alanxz I have a build error on travis.

```
/home/travis/build/macintoshplus/rabbitmq-c/librabbitmq/amqp_openssl.c: In function ‘setup_openssl’:
/home/travis/build/macintoshplus/rabbitmq-c/librabbitmq/amqp_openssl.c:586:3: error: ‘OPENSSL_config’ is deprecated (declared at /usr/include/openssl/conf.h:92) [-Werror=deprecated-declarations]
   OPENSSL_config(NULL);
   ^
/home/travis/build/macintoshplus/rabbitmq-c/librabbitmq/amqp_openssl.c: In function ‘amqp_uninitialize_ssl_library’:
/home/travis/build/macintoshplus/rabbitmq-c/librabbitmq/amqp_openssl.c:657:3: error: ‘ERR_remove_state’ is deprecated (declared at /usr/include/openssl/err.h:248) [-Werror=deprecated-declarations]
   ERR_remove_state(0);
   ^
cc1: all warnings being treated as errors
make[2]: *** [librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl.c.o] Error 1
make[1]: *** [librabbitmq/CMakeFiles/rabbitmq.dir/all] Error 2
make: *** [all] Error 2
```
https://travis-ci.org/macintoshplus/rabbitmq-c/jobs/351321057

For appveyor, how to select the OpenSSL version ?
I have an older config who using this build: http://slproweb.com/products/Win32OpenSSL.html

**Comment by macintoshplus** [comment]
Log of build with cmake in my computer:

```
➜  build git:(ossl-v110) cmake -DBUILD_SHARED_LIBS=ON -DENABLE_SSL_SUPPORT=ON ..
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE not specified. Creating Release build
-- Found C inline keyword: inline
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for socket
-- Looking for socket - found
-- Looking for poll
-- Looking for poll - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for posix_spawnp in rt
-- Looking for posix_spawnp in rt - found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.0g", minimum required is "0.9.8") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAVE_GNU90
-- Performing Test HAVE_GNU90 - Success
-- Could NOT find POPT (missing:  POPT_INCLUDE_DIR POPT_LIBRARY) 
-- Could NOT find XMLTO (missing:  XMLTO_EXECUTABLE) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Building rabbitmq as a shared library - yes
-- Building rabbitmq as a static library - yes
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jb/dev/rabbitmq-c/build
➜  build git:(ossl-v110) cmake --build .                                          
Scanning dependencies of target rabbitmq
[  1%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_framing.c.o
[  2%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_api.c.o
[  3%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_connection.c.o
[  4%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_mem.c.o
[  5%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_socket.c.o
[  6%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_table.c.o
[  7%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_url.c.o
[  8%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_tcp_socket.c.o
[ 10%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_time.c.o
[ 11%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_consumer.c.o
[ 12%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl.c.o
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c: In function ‘setup_openssl’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:579:3: warning: ‘OPENSSL_config’ is deprecated [-Wdeprecated-declarations]
   OPENSSL_config(NULL);
   ^
In file included from /usr/include/openssl/x509_vfy.h:20:0,
                 from /usr/include/openssl/x509.h:309,
                 from /usr/include/openssl/x509v3.h:14,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.h:33,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:32:
/usr/include/openssl/conf.h:92:1: note: declared here
 DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
 ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c: In function ‘amqp_uninitialize_ssl_library’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:656:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^
In file included from /usr/include/openssl/ui.h:13:0,
                 from /usr/include/openssl/engine.h:29,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:43:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
[ 13%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl_hostname_validation.c.o
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c: In function ‘amqp_matches_common_name’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:73:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
   common_name_str = (char *)ASN1_STRING_data(common_name_asn1);
   ^
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:30:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:76:55: warning: implicit declaration of function ‘strlen’ [-Wimplicit-function-declaration]
   if ((size_t)ASN1_STRING_length(common_name_asn1) != strlen(common_name_str)) {
                                                       ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:76:55: warning: incompatible implicit declaration of built-in function ‘strlen’
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:76:55: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c: In function ‘amqp_matches_subject_alternative_name’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:120:7: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
       char *dns_name = (char *)ASN1_STRING_data(current_name->d.dNSName);
       ^
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:30:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:124:11: warning: incompatible implicit declaration of built-in function ‘strlen’
           strlen(dns_name)) {
           ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:124:11: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
[ 14%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_hostcheck.c.o
[ 15%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl_bio.c.o
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_bio.c: In function ‘amqp_openssl_bio_init’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_bio.c:150:22: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   BIO_METHOD *meth = BIO_s_socket();
                      ^
[ 16%] Linking C shared library librabbitmq.so
[ 16%] Built target rabbitmq
Scanning dependencies of target rabbitmq-static
[ 17%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_framing.c.o
[ 19%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_api.c.o
[ 20%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_connection.c.o
[ 21%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_mem.c.o
[ 22%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_socket.c.o
[ 23%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_table.c.o
[ 24%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_url.c.o
[ 25%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_tcp_socket.c.o
[ 26%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_time.c.o
[ 28%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_consumer.c.o
[ 29%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_openssl.c.o
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c: In function ‘setup_openssl’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:579:3: warning: ‘OPENSSL_config’ is deprecated [-Wdeprecated-declarations]
   OPENSSL_config(NULL);
   ^
In file included from /usr/include/openssl/x509_vfy.h:20:0,
                 from /usr/include/openssl/x509.h:309,
                 from /usr/include/openssl/x509v3.h:14,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.h:33,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:32:
/usr/include/openssl/conf.h:92:1: note: declared here
 DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
 ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c: In function ‘amqp_uninitialize_ssl_library’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:656:3: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
   ERR_remove_state(0);
   ^
In file included from /usr/include/openssl/ui.h:13:0,
                 from /usr/include/openssl/engine.h:29,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl.c:43:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
[ 30%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_openssl_hostname_validation.c.o
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c: In function ‘amqp_matches_common_name’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:73:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
   common_name_str = (char *)ASN1_STRING_data(common_name_asn1);
   ^
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:30:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:76:55: warning: implicit declaration of function ‘strlen’ [-Wimplicit-function-declaration]
   if ((size_t)ASN1_STRING_length(common_name_asn1) != strlen(common_name_str)) {
                                                       ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:76:55: warning: incompatible implicit declaration of built-in function ‘strlen’
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:76:55: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c: In function ‘amqp_matches_subject_alternative_name’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:120:7: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
       char *dns_name = (char *)ASN1_STRING_data(current_name->d.dNSName);
       ^
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from /home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:30:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:124:11: warning: incompatible implicit declaration of built-in function ‘strlen’
           strlen(dns_name)) {
           ^
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_hostname_validation.c:124:11: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
[ 31%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_hostcheck.c.o
[ 32%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_openssl_bio.c.o
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_bio.c: In function ‘amqp_openssl_bio_init’:
/home/jb/dev/rabbitmq-c/librabbitmq/amqp_openssl_bio.c:150:22: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   BIO_METHOD *meth = BIO_s_socket();
                      ^
[ 33%] Linking C static library librabbitmq.a
[ 33%] Built target rabbitmq-static
Scanning dependencies of target amqp_ssl_connect
[ 34%] Building C object examples/CMakeFiles/amqp_ssl_connect.dir/amqp_ssl_connect.c.o
[ 35%] Building C object examples/CMakeFiles/amqp_ssl_connect.dir/utils.c.o
[ 37%] Building C object examples/CMakeFiles/amqp_ssl_connect.dir/unix/platform_utils.c.o
[ 38%] Linking C executable amqp_ssl_connect
[ 38%] Built target amqp_ssl_connect
Scanning dependencies of target amqp_listen
[ 39%] Building C object examples/CMakeFiles/amqp_listen.dir/amqp_listen.c.o
[ 40%] Building C object examples/CMakeFiles/amqp_listen.dir/utils.c.o
[ 41%] Building C object examples/CMakeFiles/amqp_listen.dir/unix/platform_utils.c.o
[ 42%] Linking C executable amqp_listen
[ 42%] Built target amqp_listen
Scanning dependencies of target amqp_rpc_sendstring_client
[ 43%] Building C object examples/CMakeFiles/amqp_rpc_sendstring_client.dir/amqp_rpc_sendstring_client.c.o
[ 44%] Building C object examples/CMakeFiles/amqp_rpc_sendstring_client.dir/utils.c.o
[ 46%] Building C object examples/CMakeFiles/amqp_rpc_sendstring_client.dir/unix/platform_utils.c.o
[ 47%] Linking C executable amqp_rpc_sendstring_client
[ 47%] Built target amqp_rpc_sendstring_client
Scanning dependencies of target amqp_bind
[ 48%] Building C object examples/CMakeFiles/amqp_bind.dir/amqp_bind.c.o
[ 49%] Building C object examples/CMakeFiles/amqp_bind.dir/utils.c.o
[ 50%] Building C object examples/CMakeFiles/amqp_bind.dir/unix/platform_utils.c.o
[ 51%] Linking C executable amqp_bind
[ 51%] Built target amqp_bind
Scanning dependencies of target amqp_sendstring
[ 52%] Building C object examples/CMakeFiles/amqp_sendstring.dir/amqp_sendstring.c.o
[ 53%] Building C object examples/CMakeFiles/amqp_sendstring.dir/utils.c.o
[ 55%] Building C object examples/CMakeFiles/amqp_sendstring.dir/unix/platform_utils.c.o
[ 56%] Linking C executable amqp_sendstring
[ 56%] Built target amqp_sendstring
Scanning dependencies of target amqp_connect_timeout
[ 57%] Building C object examples/CMakeFiles/amqp_connect_timeout.dir/amqp_connect_timeout.c.o
[ 58%] Building C object examples/CMakeFiles/amqp_connect_timeout.dir/utils.c.o
[ 59%] Building C object examples/CMakeFiles/amqp_connect_timeout.dir/unix/platform_utils.c.o
[ 60%] Linking C executable amqp_connect_timeout
[ 60%] Built target amqp_connect_timeout
Scanning dependencies of target amqp_listenq
[ 61%] Building C object examples/CMakeFiles/amqp_listenq.dir/amqp_listenq.c.o
[ 62%] Building C object examples/CMakeFiles/amqp_listenq.dir/utils.c.o
[ 64%] Building C object examples/CMakeFiles/amqp_listenq.dir/unix/platform_utils.c.o
[ 65%] Linking C executable amqp_listenq
[ 65%] Built target amqp_listenq
Scanning dependencies of target amqp_exchange_declare
[ 66%] Building C object examples/CMakeFiles/amqp_exchange_declare.dir/amqp_exchange_declare.c.o
[ 67%] Building C object examples/CMakeFiles/amqp_exchange_declare.dir/utils.c.o
[ 68%] Building C object examples/CMakeFiles/amqp_exchange_declare.dir/unix/platform_utils.c.o
[ 69%] Linking C executable amqp_exchange_declare
[ 69%] Built target amqp_exchange_declare
Scanning dependencies of target amqp_producer
[ 70%] Building C object examples/CMakeFiles/amqp_producer.dir/amqp_producer.c.o
[ 71%] Building C object examples/CMakeFiles/amqp_producer.dir/utils.c.o
[ 73%] Building C object examples/CMakeFiles/amqp_producer.dir/unix/platform_utils.c.o
[ 74%] Linking C executable amqp_producer
[ 74%] Built target amqp_producer
Scanning dependencies of target amqp_consumer
[ 75%] Building C object examples/CMakeFiles/amqp_consumer.dir/amqp_consumer.c.o
[ 76%] Building C object examples/CMakeFiles/amqp_consumer.dir/utils.c.o
[ 77%] Building C object examples/CMakeFiles/amqp_consumer.dir/unix/platform_utils.c.o
[ 78%] Linking C executable amqp_consumer
[ 78%] Built target amqp_consumer
Scanning dependencies of target amqp_unbind
[ 79%] Building C object examples/CMakeFiles/amqp_unbind.dir/amqp_unbind.c.o
[ 80%] Building C object examples/CMakeFiles/amqp_unbind.dir/utils.c.o
[ 82%] Building C object examples/CMakeFiles/amqp_unbind.dir/unix/platform_utils.c.o
[ 83%] Linking C executable amqp_unbind
[ 83%] Built target amqp_unbind
Scanning dependencies of target test_status_enum
[ 84%] Building C object tests/CMakeFiles/test_status_enum.dir/test_status_enum.c.o
[ 85%] Linking C executable test_status_enum
[ 85%] Built target test_status_enum
Scanning dependencies of target test_merge_capabilities
[ 86%] Building C object tests/CMakeFiles/test_merge_capabilities.dir/test_merge_capabilities.c.o
[ 87%] Linking C executable test_merge_capabilities
[ 87%] Built target test_merge_capabilities
Scanning dependencies of target test_hostcheck
[ 88%] Building C object tests/CMakeFiles/test_hostcheck.dir/test_hostcheck.c.o
[ 89%] Building C object tests/CMakeFiles/test_hostcheck.dir/__/librabbitmq/amqp_hostcheck.c.o
[ 91%] Linking C executable test_hostcheck
[ 91%] Built target test_hostcheck
Scanning dependencies of target test_basic
[ 92%] Building C object tests/CMakeFiles/test_basic.dir/test_basic.c.o
[ 93%] Linking C executable test_basic
[ 93%] Built target test_basic
Scanning dependencies of target test_tables
[ 94%] Building C object tests/CMakeFiles/test_tables.dir/test_tables.c.o
[ 95%] Linking C executable test_tables
[ 95%] Built target test_tables
Scanning dependencies of target test_sasl_mechanism
[ 96%] Building C object tests/CMakeFiles/test_sasl_mechanism.dir/test_sasl_mechanism.c.o
[ 97%] Linking C executable test_sasl_mechanism
[ 97%] Built target test_sasl_mechanism
Scanning dependencies of target test_parse_url
[ 98%] Building C object tests/CMakeFiles/test_parse_url.dir/test_parse_url.c.o
[100%] Linking C executable test_parse_url
[100%] Built target test_parse_url
```

**Comment by sigiesec** [comment]
In my branch https://github.com/sigiesec/rabbitmq-c/tree/ossl-v110, I added a travis build which installs openssl 1.1.0, which seems to work (https://travis-ci.org/sigiesec/rabbitmq-c/jobs/347853102#L470), but for some reason the build still claims it uses openssl 1.0.1f (https://travis-ci.org/sigiesec/rabbitmq-c/jobs/347853102#L730)

**Comment by macintoshplus** [comment]
@sigiesec The  libssl-dev package is up to date ?

**Comment by sigiesec** [comment]
@macintoshplus Ah yes, that was missing, thanks for pointing me to that :) Now the travis-ci job gets the same errors as your local build:
https://travis-ci.org/sigiesec/rabbitmq-c/jobs/352307302#L2051

**Comment by macintoshplus** [comment]
I do not understand the need to update the code to build with OpenSSL 1.1. The Surry repository contains a version of this library linked to OpenSSL 1.1. Where's the source code?

Here is the library installed:
```
sudo apt-cache policy libssl1.1
libssl1.1:
  Installed : 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Candidate : 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
 Table de version :
 *** 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

Here are the related libraries `librabbitmq`:
```
ldd /usr/lib/x86_64-linux-gnu/librabbitmq.so.4
	linux-vdso.so.1 =>  (0x00007ffcb63dc000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f5da9dde000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f5da9963000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5da975b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5da953e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5da9174000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5da8f70000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5daa25d000)
```

**Comment by sigiesec** [comment]
In my branch, I now managed to build rabbitmq-c against openssl 1.1.0g: https://travis-ci.org/sigiesec/rabbitmq-c/jobs/352372476

I am currently trying to also build with openssl 1.1.0g on appveyor

**Comment by sigiesec** [comment]
@macintoshplus Probably they just build without -Werror or specifically disable deprecation warnings?

**Comment by sigiesec** [comment]
@macintoshplus Ah, it's the other way round: the travis build script specifically adds -Werror. In https://launchpadlibrarian.net/332806624/buildlog_ubuntu-artful-arm64.librabbitmq_0.8.0-1+ubuntu17.10.1+deb.sury.org+1_BUILDING.txt.gz, you can also see the deprecation warnings, but they don't let the build fail.

**Comment by sigiesec** [comment]
@alanxz I now added a build job on travis-ci that uses openssl 1.1, and migrated the Appveyor jobs to openssl 1.1 in my branch https://github.com/sigiesec/rabbitmq-c/tree/ossl-v110, based on the branch of this PR.

**Comment by macintoshplus** [comment]
@sigiesec Same result with deprecation resolved.

@alanxz My PR is #481
* build succes on Travis
* build succes on AppVeyor
* OpensSSL 1.1 deprecations solved
* Other errors solved

**Comment by sigiesec** [comment]
@macintoshplus Oh, I also opened a PR #482 now ;) There are some slight differences between our variants... for some points I am not sure what is better. Maybe @alanxz can decide which one to use, or to pick fragments of both of them.

**Comment by macintoshplus** [comment]
@sigiesec No problem. I'm not shure when my way is better or not!

**Comment by sigiesec** [comment]
@alanxz Is there a chance you have a look and maybe merge one of the PRs that implement openssl 1.1.0 support, and make a new release? We look for that quite urgently, and would very much prefer to use a released version.

**Comment by sigiesec** [comment]
@alanxz Ping?

**Comment by alanxz** [comment]
Sorry for the delay. I have been reviewing it slowly.  I hopefully will
have a minute to send the first round of comments this evening.

**Comment by sigiesec** [comment]
Sounds great :)

**Comment by macintoshplus** [comment]
Hi @alanxz,
The support for OpenSSL 1.1 is completed ? When you release the next version ?

**Comment by alanxz** [comment]
@macintoshplus rabbitmq-c v0.9.0 has been released: https://github.com/alanxz/rabbitmq-c/releases/tag/v0.9.0

**Comment by vedhu63w** [comment]
Hi @alanxz,
Just a minor thing. You might want to upgrade the minimum requirement of openssl in the CMakeLists(still using 0.9.8). My rabbitmq-0.9 installation kept linking to openssl-0.9.* (Installed as default in our system). There were no compile errors. only during the application runtime, we noticed the issue.
