### ISSUE TITLE
Failure to build with OpenSSL 1.1.1l

### ISSUE THREAD

**Issue by w3sip** [alanxz/rabbitmq-c#713]
Trying to build v0.10.0 with OpenSSL. Getting 
```build/rabbitmq-c/librabbitmq/amqp_openssl.c:697:3: error: implicit declaration of function 'ENGINE_cleanup' [-Werror,-Wimplicit-function-declaration]```

We used to build with OpenSSL 1.0.2o, but need to upgrade.

**Comment by w3sip** [comment]
This seems relevant: https://githubmemory.com/repo/c4games/engine-x/issues/359?page=2

Looks like some parts of OpenSSL (DSO) aren't present on Apple Silicon. Not sure what it means in context of this project, but wondering if this is something that is likely to be prioritized in the next few weeks/months.

**Comment by alanxz** [comment]
This is likely fixed by #753
