### ISSUE TITLE
va_start undefined behavior/compile error

### ISSUE THREAD

**Issue by Kokan** [alanxz/rabbitmq-c#440]
Hello,

The current master ( 4b337fe ) does not compile with clang 3.9 and -Werror option.
There are multiple reason for that:
* #439 I gave a possible workaround for the first one, configure detection issue.
* The `va_start` as it is used has undefined behavior, and clang with -Werror does not compile because of it.

> /home/travis/build/alanxz/rabbitmq-c/librabbitmq/amqp_socket.c:1503:16: error: 
>       passing an object that undergoes default argument promotion to 'va_start'
>       has undefined behavior [-Werror,-Wvarargs]
>   va_start(vl, sasl_method);
>                ^

I would submit a change to fix those, but it seems to me that the two function (`amqp_login` and `amqp_login_with_properties` ) is part of the API, and my solution (use int instead of the enum) would broke the API.

Would it be okay to broke the API ?
What other solution could we do ?

Some note:
* It works fine with **clang-3.8** and **clang-4.0**.
* Although I do not think OS/Distro is relevant, but I tried with Ubuntu 17.04.

**Comment by alanxz** [comment]
Its funny it works with v3.8, doesn't work with v3.9, but works again with v4.0.

I don't think converting an enum -> int is going to break ABI (int is the default representation for an enum), and an enum will promote to int, so it may not break the API.

Seems like changing that parameter in `amqp_login` and `amqp_login_with_properties` is a reasonable workaround.

See also: systemd/systemd#5783, libuv/libuv#987

**Comment by Kokan** [comment]
Thank you, I did the update in the #439 
Also may I suggest to run travis regularly for the master ? (It is possible via cron jobs now.)
